name: "Alma Connect"
description: "Connecting you to your alma mater"

author: "AlmaConnect"

url: "http://alma-connect.github.io"
baseurl: ""
#baseurl: "/techblog"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: almaconnect.com
ga_tracking_id: UA-49058929-1
